spring:
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cas?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    hikari:
      maximum-pool-size: 40
      minimum-idle: 40
      idle-timeout: 150000
      connection-timeout: 3000
      connection-test-query: select 1
  redis:
    cluster:
      nodes:
        - 120.78.12.115:6380
        - 120.78.12.115:6381
        - 120.78.12.115:6382
        - 120.78.12.115:6383
        - 120.78.12.115:6384
        - 120.78.12.115:6385
      max-redirects: 3  # 获取失败 最大重定向次数
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10    # 连接池中的最大空闲连接
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle:  5     # 连接池中的最小空闲连接
    timeout: 6000  # 连接超时时长（毫秒）

server:
  port: 7003


security:
  cas:
    server:
      host: http://www.cas.com:9080/cas
      login: ${security.cas.server.host}/login
      logout: ${security.cas.server.host}/logout
    service:
      host: http://www.backend.com:${server.port}
      login: /login
      logout: /logout

