spring:
  redis:
    cluster:
      nodes:
        - 120.78.12.115:6380
        - 120.78.12.115:6381
        - 120.78.12.115:6382
        - 120.78.12.115:6383
        - 120.78.12.115:6384
        - 120.78.12.115:6385
      max-redirects: 3  # 获取失败 最大重定向次数
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10    # 连接池中的最大空闲连接
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle:  5     # 连接池中的最小空闲连接
    timeout: 6000  # 连接超时时长（毫秒）

server:
  port: 7001
